export enum BREADCRUMB_EVENT  {
  "BREADCRUMB_UPDATE"="BREADCRUMB_UPDATE",
  "BREADCRUMB_ADD"="BREADCRUMB_ADD",
  "BREADCRUMB_REMOVE"="BREADCRUMB_REMOVE",
  "BREADCRUMB_CLEAR"="BREADCRUMB_CLEAR",
}

export enum INFINITE_LOADER_EVENT  {
  START_INFINITE_LOADER ="START_INFINITE_LOADER",
  STOP_INFINITE_LOADER ="STOP_INFINITE_LOADER",
  RESET_INFINITE_LOADER ="RESET_INFINITE_LOADER",
}

export enum LANGUAGE_EVENT  {
  "LANGUAGE_CHANGE"="LANGUAGE_CHANGE",
}
