import { ethers } from "hardhat";
import fs from "fs";
import path from "path";

// Declarar __dirname para TypeScript
declare const __dirname: string;

/*  ───────────────────────── helpers ─────────────────────────  */
// Directorio raíz del proyecto (un nivel arriba de scripts)
const PROJECT_ROOT = path.resolve(__dirname, "..");
const ARTIFACTS_DIR = path.join(PROJECT_ROOT, "artifacts");
const BACK_DIR = path.join(PROJECT_ROOT, "deployments");
// Directorio compartido con el backend via Docker volume
const SHARED_DIR = process.env.SHARED_DIR || "";

function saveABIandAddress(contractName: string, address: string) {
  const artifactPath = path.join(
    ARTIFACTS_DIR,
    "contracts",
    `${contractName}.sol`,
    `${contractName}.json`
  );

  if (!fs.existsSync(artifactPath)) {
    console.warn(`⚠️  Advertencia: No se encontró el artefacto para ${contractName}`);
    return;
  }

  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf-8"));
  const data = { contractName, abi: artifact.abi, address };

  // Guardar en directorio local de deployments
  fs.mkdirSync(BACK_DIR, { recursive: true });
  fs.writeFileSync(
    path.join(BACK_DIR, `${contractName}.json`),
    JSON.stringify(data, null, 2)
  );

  // Guardar en directorio compartido (Docker volume)
  if (SHARED_DIR) {
    const sharedContracts = path.join(SHARED_DIR, "contracts");
    fs.mkdirSync(sharedContracts, { recursive: true });
    fs.writeFileSync(
      path.join(sharedContracts, `${contractName}.json`),
      JSON.stringify(data, null, 2)
    );
  }
}

/** Guardar solo ABI (sin address) para contratos dinámicos */
function saveABIOnly(contractName: string) {
  const artifactPath = path.join(
    ARTIFACTS_DIR,
    "contracts",
    `${contractName}.sol`,
    `${contractName}.json`
  );

  if (!fs.existsSync(artifactPath)) {
    console.warn(`⚠️  Advertencia: No se encontró el artefacto para ${contractName}`);
    return;
  }

  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf-8"));
  const data = { contractName, abi: artifact.abi };

  if (SHARED_DIR) {
    const sharedContracts = path.join(SHARED_DIR, "contracts");
    fs.mkdirSync(sharedContracts, { recursive: true });
    fs.writeFileSync(
      path.join(sharedContracts, `${contractName}.json`),
      JSON.stringify(data, null, 2)
    );
  }
}

/** Exportar direcciones como .env y señalizar que el deploy terminó */
function exportToSharedVolume(addresses: Record<string, string>) {
  if (!SHARED_DIR) return;

  console.log(`\n📦 Exportando al volumen compartido: ${SHARED_DIR}`);

  // Escribir contracts.env con las direcciones
  const envLines = [
    `# Auto-generated by deploy.ts - ${new Date().toISOString()}`,
    `FLEXIBILITY_TOKEN_ADDRESS=${addresses.FlexibilityToken}`,
    `TREASURY_ADDRESS=${addresses.Treasury}`,
    `FLEXIBILITY_NFT_ADDRESS=${addresses.FlexibilityNFT}`,
    `PARTICIPANT_REGISTRY_ADDRESS=${addresses.ParticipantRegistry}`,
    `MARKET_FACTORY_ADDRESS=${addresses.MarketFactory}`,
  ];
  fs.writeFileSync(path.join(SHARED_DIR, "contracts.env"), envLines.join("\n") + "\n");
  console.log("  ✅ contracts.env escrito");

  // Escribir deployments.json
  fs.writeFileSync(
    path.join(SHARED_DIR, "deployments.json"),
    JSON.stringify({ timestamp: new Date().toISOString(), contracts: addresses }, null, 2)
  );
  console.log("  ✅ deployments.json escrito");

  // Señal de que el deploy ha terminado
  fs.writeFileSync(path.join(SHARED_DIR, ".deployed"), new Date().toISOString());
  console.log("  ✅ Señal .deployed creada");
}

async function main() {
  /* 1 ───── cuenta deployer ───── */
  const [deployer, account1] = await ethers.getSigners();
  console.log(`\n👤  Deployer: ${deployer.address}`);
  console.log(`👤  Backend Admin (account1): ${account1.address}\n`);

  /* 2 ───── FlexibilityToken ───── */
  console.log("📝 Deploying FlexibilityToken...");
  const FlexToken = await ethers.getContractFactory("FlexibilityToken");
  const token = await FlexToken.deploy();
  await token.waitForDeployment();
  const tokenAddr = await token.getAddress();
  console.log(`🪙  FlexibilityToken        → ${tokenAddr}`);

  /* 2.1 ───── Grant roles to backend admin (account1) on FlexibilityToken ───── */
  const DEFAULT_ADMIN_ROLE = "0x0000000000000000000000000000000000000000000000000000000000000000";
  const MINTER_ROLE = await token.MINTER_ROLE();

  console.log("\n🔐 Granting roles to backend admin on FlexibilityToken...");
  await token.grantRole(DEFAULT_ADMIN_ROLE, account1.address);
  console.log(`✅ DEFAULT_ADMIN_ROLE granted to ${account1.address} on FlexibilityToken`);
  await token.grantRole(MINTER_ROLE, account1.address);
  console.log(`✅ MINTER_ROLE granted to ${account1.address} on FlexibilityToken`);

  /* 3 ───── Treasury ───── */
  console.log("\n📝 Deploying Treasury...");
  const Treasury = await ethers.getContractFactory("Treasury");
  const treasury = await Treasury.deploy(tokenAddr, deployer.address);
  await treasury.waitForDeployment();
  const treasuryAddr = await treasury.getAddress();
  console.log(`💰 Treasury                → ${treasuryAddr}`);

  /* 3.1 ───── Grant DEFAULT_ADMIN_ROLE to backend admin (account1) on Treasury ───── */
  console.log("\n🔐 Granting DEFAULT_ADMIN_ROLE to backend admin on Treasury...");
  await treasury.grantRole(DEFAULT_ADMIN_ROLE, account1.address);
  console.log(`✅ DEFAULT_ADMIN_ROLE granted to ${account1.address} on Treasury`);

  /* 5 ───── FlexibilityNFT ───── */
  console.log("\n📝 Deploying FlexibilityNFT...");
  const FlexibilityNFT = await ethers.getContractFactory("FlexibilityNFT");
  const flexibilityNFT = await FlexibilityNFT.deploy();
  await flexibilityNFT.waitForDeployment();
  const flexibilityNFTAddr = await flexibilityNFT.getAddress();
  console.log(`🎨 FlexibilityNFT          → ${flexibilityNFTAddr}`);

  /* 5.1 ───── Grant DEFAULT_ADMIN_ROLE to backend admin (account1) on FlexibilityNFT ───── */
  console.log("\n🔐 Granting DEFAULT_ADMIN_ROLE to backend admin on FlexibilityNFT...");
  await flexibilityNFT.grantRole(DEFAULT_ADMIN_ROLE, account1.address);
  console.log(`✅ DEFAULT_ADMIN_ROLE granted to ${account1.address} on FlexibilityNFT`);

  /* 6 ───── ParticipantRegistry ───── */
  console.log("\n📝 Deploying ParticipantRegistry...");
  const ParticipantRegistry = await ethers.getContractFactory("ParticipantRegistry");
  const participantRegistry = await ParticipantRegistry.deploy();
  await participantRegistry.waitForDeployment();
  const participantRegistryAddr = await participantRegistry.getAddress();
  console.log(`📋 ParticipantRegistry     → ${participantRegistryAddr}`);

  /* 6.1 ───── Grant REGISTRAR_ROLE to backend admin (account1) ───── */
  const REGISTRAR_ROLE = await participantRegistry.REGISTRAR_ROLE();
  await participantRegistry.grantRole(REGISTRAR_ROLE, account1.address);
  console.log(`📋 REGISTRAR_ROLE granted to ${account1.address}`);

  /* 6.2 ───── Grant DEFAULT_ADMIN_ROLE to backend admin (account1) on ParticipantRegistry ───── */
  console.log("\n🔐 Granting DEFAULT_ADMIN_ROLE to backend admin on ParticipantRegistry...");
  await participantRegistry.grantRole(DEFAULT_ADMIN_ROLE, account1.address);
  console.log(`✅ DEFAULT_ADMIN_ROLE granted to ${account1.address} on ParticipantRegistry`);

  /* 7 ───── MarketFactory ───── */
  console.log("\n📝 Deploying MarketFactory...");
  const MFactory = await ethers.getContractFactory("MarketFactory");
  console.log(
    "Constructor:",
    MFactory.interface.fragments.find((f) => f.type === "constructor")
  );
  const marketFactory = await MFactory.deploy(participantRegistryAddr);
  await marketFactory.waitForDeployment();
  const mFactoryAddr = await marketFactory.getAddress();
  console.log(`🏭 MarketFactory           → ${mFactoryAddr}`);

  /* 7.1 ───── Grant roles to backend admin (account1) on MarketFactory ───── */
  console.log("\n🔐 Granting roles to backend admin on MarketFactory...");
  await marketFactory.grantRole(DEFAULT_ADMIN_ROLE, account1.address);
  console.log(`✅ DEFAULT_ADMIN_ROLE granted to ${account1.address} on MarketFactory`);
  const MARKETPLACE_ADMIN = await marketFactory.MARKETPLACE_ADMIN();
  await marketFactory.grantRole(MARKETPLACE_ADMIN, account1.address);
  console.log(`✅ MARKETPLACE_ADMIN granted to ${account1.address} on MarketFactory`);

  /* 8 ───── guardar artefactos para el back‑end ───── */
  console.log("\n💾 Guardando artefactos y direcciones...");
  console.log(`📁 Directorio de deployment: ${BACK_DIR}`);

  fs.mkdirSync(BACK_DIR, { recursive: true });
  saveABIandAddress("FlexibilityToken", tokenAddr);
  saveABIandAddress("Treasury", treasuryAddr);
  saveABIandAddress("FlexibilityNFT", flexibilityNFTAddr);
  saveABIandAddress("ParticipantRegistry", participantRegistryAddr);
  saveABIandAddress("MarketFactory", mFactoryAddr);

  // Guardar ABIs de contratos dinámicos (sin address)
  saveABIOnly("Market");
  saveABIOnly("MarketSession");

  // Guardar contratos dinámicos (Market y MarketSession)
  const dynamicContracts = {
    MarketSession: { address: "Deployed by MarketFactory", note: "Dynamic deployment" },
    Market: { address: "Deployed by MarketSession", note: "Dynamic deployment" }
  };

  fs.writeFileSync(
    path.join(BACK_DIR, "DynamicContracts.json"),
    JSON.stringify(dynamicContracts, null, 2)
  );

  /* Archivo TypeScript con todas las direcciones */
  const ts = `// Direcciones de contratos desplegados
// Generado automáticamente - No editar manualmente

export const FlexibilityTokenAddress     = "${tokenAddr}";
export const TreasuryAddress             = "${treasuryAddr}";
export const FlexibilityNFTAddress       = "${flexibilityNFTAddr}";
export const ParticipantRegistryAddress  = "${participantRegistryAddr}";
export const MarketFactoryAddress        = "${mFactoryAddr}";

// Contratos dinámicos (desplegados por factories)
export const MarketSessionAddress        = ""; // Deployed by MarketFactory
export const MarketAddress               = ""; // Deployed by MarketSession
`;
  fs.writeFileSync(path.join(BACK_DIR, "contractAddresses.ts"), ts.trim());

  /* 9 ───── exportar al volumen compartido Docker ───── */
  const allAddresses = {
    FlexibilityToken: tokenAddr,
    Treasury: treasuryAddr,
    FlexibilityNFT: flexibilityNFTAddr,
    ParticipantRegistry: participantRegistryAddr,
    MarketFactory: mFactoryAddr,
  };
  exportToSharedVolume(allAddresses);

  console.log("\n✅ Sistema desplegado y datos exportados al back‑end.");
  console.log("\n📊 Resumen de contratos desplegados:");
  console.log("════════════════════════════════════════════════════════════");
  console.log(`FlexibilityToken      : ${tokenAddr}`);
  console.log(`Treasury              : ${treasuryAddr}`);
  console.log(`FlexibilityNFT        : ${flexibilityNFTAddr}`);
  console.log(`ParticipantRegistry   : ${participantRegistryAddr}`);
  console.log(`MarketFactory         : ${mFactoryAddr}`);
  console.log("════════════════════════════════════════════════════════════");
  console.log("\n🔐 Roles asignados a backend admin (account1):");
  console.log(`   ${account1.address}`);
  console.log("   - DEFAULT_ADMIN_ROLE on FlexibilityToken");
  console.log("   - MINTER_ROLE on FlexibilityToken");
  console.log("   - DEFAULT_ADMIN_ROLE on Treasury");
  console.log("   - DEFAULT_ADMIN_ROLE on FlexibilityNFT");
  console.log("   - DEFAULT_ADMIN_ROLE on ParticipantRegistry");
  console.log("   - REGISTRAR_ROLE on ParticipantRegistry");
  console.log("   - DEFAULT_ADMIN_ROLE on MarketFactory");
  console.log("   - MARKETPLACE_ADMIN on MarketFactory");
  console.log("════════════════════════════════════════════════════════════\n");
}

main().catch((err) => {
  console.error("❌  Deployment failed:", err);
  process.exitCode = 1;
});
